rag360-agent:
  title: RAG360 Agent
  description: RAG360 agent for retrieving data from MarkLogic for RAG use cases.
  instructions: You are a helpful assistant.
  drivers: []
  rules:
    rules:
      - prompt: Be polite and concise.
  workflows:
    default:
      name: Default
      description: Answer questions.
      parameters: {}
      required: []
      preprocess: []
      context:
        - module: hello-world
          id: hello-world
          title: Hello World
      generation:
        - module: passthrough
      postprocess: []
